Repository WeCanWebserv/Webserv, pull requests merged in 2022-09, with the labels that each got.

#21 Add Logger
  webserv/src/Logger.cpp
  webserv/src/Logger.hpp
Labels: feat

#6 Parse HTTP Request message
  .gitignore
  webserv/__test__/requesttest.cpp
  webserv/src/request/body.hpp
  webserv/src/request/field_value.hpp
  webserv/src/request/header.hpp
  webserv/src/request/request.cpp
  webserv/src/request/request.hpp
  webserv/src/request/request_parser.cpp
  webserv/src/request/request_parser.hpp
  webserv/src/request/startline.hpp
Labels: feat

#14 Implement Request process logic
  webserv/include/Response.hpp
  webserv/src/Response.cpp
  webserv/src/response/MediaType.cpp
  webserv/src/response/MediaType.hpp
  webserv/src/response/ReasonPhrase.cpp
  webserv/src/response/ReasonPhrase.hpp
  webserv/src/response/Response.cpp
  webserv/src/response/Response.hpp
  webserv/src/response/UriParser.cpp
  webserv/src/response/UriParser.hpp
  webserv/src/response/test/404.html
  webserv/src/response/test/Makefile
  webserv/src/response/test/index.html
  webserv/src/response/test/main.cpp
Labels: feat

#25 Feature/#24
  webserv/src/request/__test__/requesttest.cpp
  webserv/src/request/request.cpp
  webserv/src/request/request_parser.cpp
  webserv/src/request/request_parser.hpp
Labels: bug

#26 epoll loop에 Response 적용하기
  webserv/src/Connection.hpp
  webserv/src/ServerManager.cpp
  webserv/src/ServerManager.hpp
  webserv/src/response/Response.cpp
  webserv/src/response/Response.hpp
Labels: fix

#31 #15 Apply HTTP pipelining using queue
  webserv/src/request/__test__/requesttest.cpp
  webserv/src/request/body.hpp
  webserv/src/request/header.hpp
  webserv/src/request/request.cpp
  webserv/src/request/request.hpp
  webserv/src/request/request_manager.cpp
  webserv/src/request/request_manager.hpp
  webserv/src/request/request_parser.cpp
Labels: feat

#32 Implement CGI
  webserv/src/ServerManager.cpp
  webserv/src/libft.cpp
  webserv/src/libft.hpp
  webserv/src/response/Cgi.cpp
  webserv/src/response/Cgi.hpp
  webserv/src/response/Response.cpp
  webserv/src/response/Response.hpp
  webserv/src/response/UriParser.cpp
  webserv/src/response/UriParser.hpp
  webserv/src/response/test_uriparser/Makefile
  webserv/src/response/test_uriparser/main.cpp
Labels: feat

#34 Redirect response
  webserv/src/response/Response.cpp
Labels: feat

#40 string stream의 copy constructor 문제를 빼고 오류가 안나도록 코드 수정
  .gitignore
  webserv/Makefile
  webserv/src/ConfigParser.cpp
  webserv/src/ConfigParser.hpp
  webserv/src/Connection.hpp
  webserv/src/ServerManager.cpp
  webserv/src/request/__test__/requesttest.cpp
  webserv/src/request/body.hpp
  webserv/src/request/header.hpp
  webserv/src/request/request.cpp
  webserv/src/request/request_manager.cpp
  webserv/src/request/request_parser.cpp
  webserv/src/request/request_parser.hpp
  webserv/src/response/Response.cpp
  webserv/src/response/Response.hpp
Labels: hotfix

#37 Refactor Response, Cgi
  webserv/src/response/Cgi.cpp
  webserv/src/response/Cgi.hpp
  webserv/src/response/Response.cpp
Labels: refactor, fix

#45 #38 fix: add copy ctor all class in RequestManager
  webserv/src/request/body.hpp
  webserv/src/request/field_value.hpp
  webserv/src/request/header.hpp
  webserv/src/request/request.cpp
  webserv/src/request/request.hpp
  webserv/src/request/request_manager.cpp
  webserv/src/request/request_manager.hpp
Labels: hotfix

#48 Hotfix/#46
  webserv/Makefile
  webserv/src/ServerManager.cpp
  webserv/src/ServerManager.hpp
  webserv/src/request/field_value.hpp
  webserv/src/request/header.hpp
  webserv/src/request/request_manager.cpp
  webserv/src/request/request_manager.hpp
  webserv/src/request/request_parser.cpp
  webserv/src/response/Cgi.cpp
  webserv/src/response/Cgi.hpp
  webserv/src/response/Response.cpp
  webserv/src/response/Response.hpp
  webserv/src/response/Uri.cpp
  webserv/src/response/Uri.hpp
  webserv/src/response/UriParser.cpp
  webserv/src/response/UriParser.hpp
  webserv/src/response/test_uriparser/Makefile
  webserv/src/response/test_uriparser/main.cpp
Labels: bug, fix

#56 #51 refactor: fix error code to 413 error
  webserv/src/request/request_parser.cpp
Labels: fix

#68 Fix cgi pipe to block
  webserv/src/ServerManager.cpp
  webserv/src/response/Cgi.cpp
Labels: bug, fix
